const actions = {
  UPDATE_SCROLL_Y:          'UPDATE_SCROLL_Y',
  UPDATE_SCROLL_UP:         'UPDATE_SCROLL_UP',
  UPDATE_SCROLL_DOWN:       'UPDATE_SCROLL_DOWN',
  UPDATE_SCROLL_DIRECTION:  'UPDATE_SCROLL_DIRECTION',
  UPDATE_SCROLL_STATUS:     'UPDATE_SCROLL_STATUS',
};

export default actions;
